=== NTHU-SC/HPCI-mock-ICON/icon-model/externals/art/runctrl_examples/xml_ctrl/DONOT_USE/modes.dtd
<!ELEMENT modes (aerosol+,radio+,volcanic+)>

<!ELEMENT aerosol (kind, d_gn, d_gm, sigma_g, rho, condensation?, icoag?, lut_optics?)>
<!ATTLIST aerosol
  id  ID  #REQUIRED
  of  CDATA #REQUIRED
  type CDATA  #REQUIRED
>
<!ELEMENT radio (imis, halflife)>
<!ATTLIST radio
  id  ID  #REQUIRED
  type  CDATA #REQUIRED
>
<!ELEMENT volcanic (diam, rho)>
<!ATTLIST volcanic
  id  ID  #REQUIRED
  type  CDATA #REQUIRED
>

<!ELEMENT kind (#PCDATA)>
<!ELEMENT d_gn (#PCDATA)>
<!ELEMENT d_gm (#PCDATA)>
<!ELEMENT sigma_g (#PCDATA)>
<!ELEMENT rho (#PCDATA)>
<!ELEMENT condensation (#PCDATA)>
<!ELEMENT icoag (#PCDATA)>
<!ELEMENT lut_optics (#PCDATA)>
<!ATTLIST lut_optics
  cvar_dia  CDATA  #IMPLIED
>
<!ELEMENT imis (#PCDATA)>
<!ELEMENT halflife (#PCDATA)>
<!ELEMENT diam (#PCDATA)>

=== NTHU-SC/HPCI-mock-ICON/icon-model/externals/art/runctrl_examples/xml_ctrl/VOLAERO_RAD/modes_volaero_rad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modes SYSTEM "modes.dtd">

<modes>
  <aerosol id="sol_ait">
    <kind type="char">2mom</kind>
    <d_gn type="real">0.01E-6</d_gn>
    <sigma_g type="real">1.7</sigma_g>
    <shift2larger type="char">sol_acc</shift2larger>
    <shift_diam type="real">0.03E-6</shift_diam>
    <condensation type="int">1</condensation>
    <icoag type="int">1</icoag>
    <lut_optics type="char">inorg_ait</lut_optics>
  </aerosol>
  <aerosol id="sol_acc">
    <kind type="char">2mom</kind>
    <d_gn type="real">0.2E-6</d_gn>
    <sigma_g type="real">2.0</sigma_g>
    <condensation type="int">1</condensation>
    <icoag type="int">1</icoag>
    <lut_optics type="char">inorg_acc</lut_optics>
  </aerosol>
  <aerosol id="insol_acc">
    <kind type="char">2mom</kind>
    <d_gn type="real">0.2E-6</d_gn>
    <sigma_g type="real">2.0</sigma_g>
    <condensation type="int">1</condensation>
    <shift2mixed type="char">mixed_acc</shift2mixed>
    <icoag type="int">1</icoag>
    <lut_optics type="char">ash_acc</lut_optics>
  </aerosol>
  <aerosol id="mixed_acc">
    <kind type="char">2mom</kind>
    <d_gn type="real">0.2E-6</d_gn>
    <sigma_g type="real">2.</sigma_g>
    <condensation type="int">1</condensation>
    <icoag type="int">1</icoag>
    <lut_optics type="char">icoat15_ash_acc</lut_optics>
  </aerosol>
  <aerosol id="insol_coa">
    <kind type="char">2mom</kind>
    <d_gn type="real">2.0E-6</d_gn>
    <sigma_g type="real">2.2</sigma_g>
    <condensation type="int">1</condensation>
    <shift2mixed type="char">mixed_coa</shift2mixed>
    <icoag type="int">1</icoag>
    <lut_optics type="char">ash_coa</lut_optics>
  </aerosol>
  <aerosol id="mixed_coa">
    <kind type="char">2mom</kind>
    <d_gn type="real">2.0E-6</d_gn>
    <sigma_g type="real">2.2</sigma_g>
    <condensation type="int">1</condensation>
    <icoag type="int">1</icoag>
    <lut_optics type="char">icoat15_ash_coa</lut_optics>
  </aerosol>
  <aerosol id="giant">
    <kind type="char">2mom</kind>
    <d_gn type="real">1.200E-5</d_gn>
    <sigma_g type="real">2.0</sigma_g>
    <condensation type="int">0</condensation>
    <icoag type="int">0</icoag>
    <lut_optics type="char">ash_giant</lut_optics>
  </aerosol>
</modes>

=== NTHU-SC/HPCI-mock-ICON/icon-model/externals/art/runctrl_examples/xml_ctrl/DUST_RAD/modes_dustrad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modes SYSTEM "modes.dtd">

<modes>
  <aerosol id="dusta">
    <kind    type="char">2mom</kind>
    <d_gn    type="real">6.445E-7</d_gn>
    <d_gm    type="real">1.500E-6</d_gm>
    <sigma_g type="real">1.700E+0</sigma_g>
    <rho     type="real">2.650E+3</rho>
    <condensation type="int">0</condensation>
    <icoag type="int">0</icoag>
    <lut_optics type="char" cvar_dia="true">dust_a</lut_optics>
  </aerosol>
  <aerosol id="dustb">
    <kind    type="char">2mom</kind>
    <d_gn    type="real">3.454E-6</d_gn>
    <d_gm    type="real">6.700E-6</d_gm>
    <sigma_g type="real">1.600E+0</sigma_g>
    <rho     type="real">2.650E+3</rho>
    <condensation type="int">0</condensation>
    <icoag type="int">0</icoag>
    <lut_optics type="char" cvar_dia="true">dust_b</lut_optics>
  </aerosol>
  <aerosol id="dustc">
    <kind    type="char">2mom</kind>
    <d_gn    type="real">8.672E-6</d_gn>
    <d_gm    type="real">1.420E-5</d_gm>
    <sigma_g type="real">1.500E+0</sigma_g>
    <rho     type="real">2.650E+3</rho>
    <condensation type="int">0</condensation>
    <icoag type="int">0</icoag>
    <lut_optics type="char" cvar_dia="true">dust_c</lut_optics>
  </aerosol>
</modes>
